{% set version = "0.5.0" %}

package:
  name: haystack_bio
  version: {{ version }}

source:
  fn:  haystack_bio-{{ version }}.tar.gz
  url: https://github.com/rfarouni/haystack_bio/archive/{{ version }}.tar.gz
  md5: ed10524601688b88acd3237be0f9651e

build:
  number: 1
  skip: true # [not py27 and osx]
  entry_points:
    - haystack_pipeline=haystack.run_pipeline:main
    - haystack_hotspots= haystack.find_hotspots:main
    - haystack_motifs=haystack.find_motifs:main
    - haystack_tf_activity_plane=haystack.generate_tf_activity_plane:main
    - haystack_download_genome=haystack.download_genome:main
    - haystack_run_test=haystack.haystack_common:run_testdata

about:
    home: https://github.com/rfarouni/haystack_bio
    license: GPLv3
    summary: Epigenetic Variability and Transcription Factor Motifs Analysis Pipeline

requirements:
  build:
    - python
    - openjdk
    - meme
    - bedtools
    - sambamba
    - ucsc-bigwigaverageoverbed
    - ucsc-bedgraphtobigwig
    - bx-python 
    - numpy 
    - scipy 
    - matplotlib 
    - jinja2 
    - pandas
    - pybedtools
	- weblogo
  run:
    - openjdk
    - meme
    - bedtools
    - sambamba
    - ucsc-bigwigaverageoverbed
    - ucsc-bedgraphtobigwig
    - bx-python 
    - numpy 
    - scipy 
    - matplotlib 
    - jinja2 
    - pandas
    - pybedtools
	- weblogo

test:
  commands:
    - haystack_hotspots -h
